### ISSUE TITLE
PGN 129285 (navigation) String issue

### ISSUE THREAD

**Issue by htool** [canboat/canboatjs#171]
SignalK gives an error when I activate a MOB alert (which starts navigation to the coordinates in the alert).

pi@boatnet:~ $ candump can0 | candump2analyzer | analyzer 129285
2021-11-18-09:59:06.179 7   6 255 129285 Navigation - Route/WP Information:  Start RPS# = Unknown; nItems = 2; Database ID = Unknown; Route ID = Unknown; Navigation direction in route = Unknown; Supplementary Route/WP data available = 1; Route Name = ; WP ID 1 = 0; WP Name 1 = ; WP Latitude 1 = Unknown; WP Longitude 1 = Unknown; WP ID 2 = 1; WP Name 2 = MOB AIS SART-9727773; WP Latitude 2 = 52.4601828; WP Longitude 2 =  5.0445865

2021-11-18-13:12:35.444,7,129285,6,255,8,c0,3a,ff,ff,02,00,ff,ff
2021-11-18-13:12:35.445,7,129285,6,255,8,c1,ff,ff,e7,03,01,00,83
2021-11-18-13:12:35.446,7,129285,6,255,8,c2,00,00,03,01,00,ff,ff
2021-11-18-13:12:35.446,7,129285,6,255,8,c3,ff,7f,ff,ff,ff,7f,01
2021-11-18-13:12:35.446,7,129285,6,255,8,c4,00,16,01,4d,4f,42,20
2021-11-18-13:12:35.447,7,129285,6,255,8,c5,41,49,53,20,53,41,52
2021-11-18-13:12:35.447,7,129285,6,255,8,c6,54,2d,39,37,32,37,37
2021-11-18-13:12:35.448,7,129285,6,255,8,c7,37,33,e4,c9,44,1f,29
2021-11-18-13:12:35.467,7,129285,6,255,8,c8,be,01,03,ff,ff,ff,ff

WP Name read error:
Error: Trying to read past the end of the stream
    at BitStream.readUint8 (/usr/lib/node_modules/signalk-server/node_modules/bit-buffer/bit-buffer.js:191:10)
    at fieldTypeReaders.String with start/stop byte (/usr/lib/node_modules/signalk-server/node_modules/@canboat/canboatjs/lib/fromPgn.js:732:18)
    at readField (/usr/lib/node_modules/signalk-server/node_modules/@canboat/canboatjs/lib/fromPgn.js:498:13)
    at /usr/lib/node_modules/signalk-server/node_modules/@canboat/canboatjs/lib/fromPgn.js:235:27

3a,ff,ff,02,00,ff,ff,ff,ff,e7,03,01,00,1f,00,00,03,01,00,ff,ff,ff,7f,ff,ff,ff,7f,01,00,16,01,4d,4f,42,20,41,49,53,20,53,41,52,54,2d,39,37,32,37,37,37,32,2d,cb,44,1f,37,bf,01,03,ff,ff,ff,ff
translates to:
:ÿÿÿÿÿÿçÿÿÿÿÿÿMOB AIS SART-9727772-ËD7¿ÿÿÿÿ

It seems it trips over the 'ff' at the beginning of a string, mistaking it for length:

Adding some debug line shows the mistake for length:
  canboatjs:fromPgn String with start/stop byte: first: 255 +0ms
  canboatjs:fromPgn String with start/stop byte: len: 255 second: 255 +1ms

Changes:
fieldTypeReaders["String with start/stop byte"] = (pgn, field, bs) => {
  debug('String with start/stop byte: PGN %d field: %j bs: %j', pgn.pgn, field, bs)
  var len
  var first = bs.readUint8()
  debug('String with start/stop byte: first: %s', first)   // <---- debug
  if ( first == 0x02 ) {
    var buf = Buffer.alloc(255)
    var c
    var idx = 0
    while ( (c = bs.readUint8()) != 0x01 ) {
      buf.writeUInt8(c, idx++)
    }
    return buf.toString('ascii', 0, idx)
  } else if ( first > 0x02 ) {
    var len = first
    var second = bs.readUint8()
    debug('String with start/stop byte: len: %s second: %s', first, second)  // <---- debug
    var buf = Buffer.alloc(len)
    var idx = 0
    if ( second == 0x01 ) {
      len -= 2
    } else {
      buf.writeUInt8(second)
      idx = 1
    }
    for ( ; idx < len; idx++ ) {
      var c = bs.readUint8()
      buf.writeUInt8(c, idx)
    }
    return buf.toString('ascii', 0, idx)
  }
}

**Comment by htool** [comment]
Looks like it's not with canboatjs, but rather B&G sending packets that are non-N2K compliant. Opening a ticket with them now.

**Comment by htool** [comment]
I thought I messed up, but it's still there and still an issue. Where the issue is mostly that it gives a lot of errors in the log and the packet isn't read.
